---
development:
  cloud_name: hayqi18hk
  api_key: '829547237644758'
  api_secret: 5x4eecoELHqo8wPyTjLsLqAHp9k
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hayqi18hk
  api_key: '829547237644758'
  api_secret: 5x4eecoELHqo8wPyTjLsLqAHp9k
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hayqi18hk
  api_key: '829547237644758'
  api_secret: 5x4eecoELHqo8wPyTjLsLqAHp9k
  enhance_image_tag: true
  static_file_support: false
